[package]
name = "cjcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
colored = "2.0.0"
itertools = "0.10.5"
nom = "7.1.3"
strum = "0.24.1"
strum_macros = "0.24.3"
